### ISSUE TITLE
Any plans for android libs?

### ISSUE THREAD

**Issue by Durgesh92** [GiviMAD/rustpotter-java#1]
do you have any plans for porting this to android?

**Comment by GiviMAD** [comment]
Hi @Durgesh92,
my plan is to create another wrapper using this library https://github.com/fzyzcjy/flutter_rust_bridge to cover android and IOS usage and other flutter targets.
I think I'll start working on it in a couple of weeks as I'm taking a mental break right now.

I'm not aware of the work required to use Flutter on a native Android app. It's been some years since I did my last one. Do you know how hard/messy is to use a flutter module in a native app?
